# Generated by Django 5.2.1 on 2025-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Daily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("today_topic", models.CharField(max_length=255)),
                ("topic_description", models.CharField(max_length=255)),
            ],
        ),
    ]
