# Generated by Django 5.2.1 on 2025-06-05 05:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="daily",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="daily",
            name="today_topic",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="daily",
            name="topic_description",
            field=models.CharField(max_length=150),
        ),
    ]
