# Generated by Django 5.2.1 on 2025-06-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairy", "0002_daily_created_at_alter_daily_today_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
