# Generated by Django 5.2.1 on 2025-06-05 05:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dairy", "0003_alter_daily_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
